# Generated by Django 5.0.4 on 2024-05-07 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("card_id", models.AutoField(primary_key=True, serialize=False)),
                ("card_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "card_number",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("cvv", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bank_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bank_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customerservicepurchase",
            fields=[
                ("purchase_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("service_id", models.IntegerField(blank=True, null=True)),
                ("purchase_date", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bank_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                ("insurance_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "insurance_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bank_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                ("loan_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bank_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_mode",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "party_involved",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "transaction_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bank_app.account",
                    ),
                ),
            ],
        ),
    ]
